import { NewsItem } from '@/lib/types'

export const mockData: NewsItem[] = [
  {
    id: '1',
    title: 'Claude 3.5 Sonnet 发布：编程能力超越 GPT-4',
    summary: 'Anthropic 今日发布 Claude 3.5 Sonnet，在代码生成、逻辑推理方面表现卓越。HumanEval 编程测试得分 92%，超越 GPT-4 的 87%。支持 Artifacts 功能，可实时预览代码效果。',
    url: 'https://www.anthropic.com/news/claude-3-5-sonnet',
    source: 'Anthropic',
    source_type: '官方博客',
    category: 'tool',
    tags: ['Claude', '编程', '代码生成'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    likes: 523,
    views: 28500,
    comments: 156,
    engagement: 679,
  },
  {
    id: '2',
    title: 'OpenAI 被曝正在训练 GPT-5，参数规模达 10 万亿',
    summary: '据内部消息，OpenAI 已完成 GPT-5 的初步训练，参数规模达到惊人的 10 万亿级别。新模型在数学推理和多模态理解方面实现突破，预计 2025 年 Q2 发布。',
    url: 'https://techcrunch.com',
    source: 'TechCrunch',
    source_type: '科技媒体',
    category: 'news',
    tags: ['OpenAI', 'GPT-5', '大模型'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    likes: 412,
    views: 32100,
    comments: 203,
    engagement: 615,
  },
  {
    id: '3',
    title: 'Midjourney V7 内测开启：视频生成功能上线',
    summary: 'Midjourney 向 Plus 会员开放 V7 版本内测，新增视频生成功能。用户可通过文本描述直接生成 4 秒短视频，画质达到 1080p，运动一致性大幅提升。',
    url: 'https://www.midjourney.com',
    source: 'Midjourney',
    source_type: '官方博客',
    category: 'tool',
    tags: ['Midjourney', 'AI绘画', '视频生成'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    likes: 378,
    views: 19800,
    comments: 89,
    engagement: 467,
  },
  {
    id: '4',
    title: '阿里巴巴通义千问 2.5 开源，性能逼近 GPT-4',
    summary: '阿里云发布通义千问 2.5 开源版本，包含 7B、14B、72B 三个尺寸。其中 72B 版本在 MMLU、C-Eval 等基准测试中表现接近 GPT-4，中文理解能力领先。',
    url: 'https://qwenlm.github.io',
    source: 'QwenLM',
    source_type: '开源项目',
    category: 'tool',
    tags: ['通义千问', '开源模型', '阿里'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    likes: 445,
    views: 24500,
    comments: 178,
    engagement: 623,
  },
  {
    id: '5',
    title: '微软 Copilot Pro 涨价 50%，用户集体吐槽',
    summary: '微软宣布 Copilot Pro 订阅价格从 20 美元/月上调至 30 美元/月，涨幅 50%。官方称是因 GPT-4 Turbo 调用成本上升。Reddit 上用户纷纷表示要转向 Claude。',
    url: 'https://www.theverge.com',
    source: 'The Verge',
    source_type: '科技媒体',
    category: 'news',
    tags: ['微软', 'Copilot', '订阅服务'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    likes: 289,
    views: 15200,
    comments: 312,
    engagement: 601,
  },
  {
    id: '6',
    title: 'Runway Gen-4 发布：AI 视频进入电影级时代',
    summary: 'Runway 发布新一代视频生成模型 Gen-4，支持镜头控制、角色一致性保持、复杂场景理解。生成视频时长延长至 16 秒，画质接近专业影视水准。',
    url: 'https://runwayml.com',
    source: 'Runway',
    source_type: '官方博客',
    category: 'tool',
    tags: ['Runway', '视频生成', 'Gen-4'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    likes: 356,
    views: 18900,
    comments: 67,
    engagement: 423,
  },
  {
    id: '7',
    title: '苹果将在 WWDC 2024 发布 Siri 2.0，全面接入大模型',
    summary: '据 Bloomberg 报道，苹果将在下月 WWDC 上发布全新 Siri，深度整合自研大模型 Ajax。新版 Siri 支持连续对话、多轮记忆、跨应用操作。',
    url: 'https://www.bloomberg.com',
    source: 'Bloomberg',
    source_type: '科技媒体',
    category: 'news',
    tags: ['苹果', 'Siri', 'WWDC'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    likes: 267,
    views: 14200,
    comments: 145,
    engagement: 412,
  },
  {
    id: '8',
    title: 'Perplexity 推出 Pages 功能：AI 一键生成专业报告',
    summary: 'Perplexity AI 发布 Pages 新功能，可将搜索结果自动整理成格式化的研究报告。支持引用来源、添加图表、协作编辑，直接对标 Notion AI。',
    url: 'https://www.perplexity.ai',
    source: 'Perplexity',
    source_type: '官方博客',
    category: 'tool',
    tags: ['Perplexity', '搜索', '知识管理'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    likes: 198,
    views: 9800,
    comments: 43,
    engagement: 241,
  },
  {
    id: '9',
    title: 'Figure AI 与宝马合作，人形机器人进工厂',
    summary: '人形机器人公司 Figure AI 宣布与宝马集团达成合作，Figure 01 机器人将在宝马南卡罗来纳州工厂进行试点，承担搬运、装配等体力工作。',
    url: 'https://www.figure.ai',
    source: 'Figure AI',
    source_type: '企业新闻',
    category: 'news',
    tags: ['人形机器人', 'Figure AI', '制造业'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    likes: 234,
    views: 12800,
    comments: 89,
    engagement: 323,
  },
  {
    id: '10',
    title: 'Cursor 融资 1 亿美元，AI 编程工具估值破 10 亿',
    summary: 'AI 代码编辑器 Cursor 母公司 Anysphere 完成 1 亿美元 B 轮融资，估值达 10 亿美元。Cursor 月活已突破 50 万，成为开发者最喜爱的 AI 编程工具。',
    url: 'https://cursor.sh',
    source: 'Cursor',
    source_type: '企业新闻',
    category: 'tool',
    tags: ['Cursor', 'AI编程', '融资'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    likes: 312,
    views: 16700,
    comments: 78,
    engagement: 390,
  },
  {
    id: '11',
    title: 'Sora 被曝存在严重安全漏洞，可生成违规内容',
    summary: '安全研究人员发现 OpenAI Sora 的绕过机制存在缺陷，用户可通过特定提示词生成暴力、色情等违规视频。OpenAI 已暂停部分用户访问进行调查。',
    url: 'https://techcrunch.com',
    source: 'TechCrunch',
    source_type: '科技媒体',
    category: 'news',
    tags: ['Sora', 'OpenAI', '安全'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    likes: 445,
    views: 29800,
    comments: 567,
    engagement: 1012,
  },
  {
    id: '12',
    title: 'Hugging Face 发布 LeRobot：机器人学习开源框架',
    summary: 'Hugging Face 推出 LeRobot 开源项目，提供从数据收集到模型训练的全套工具。旨在降低机器人模仿学习的门槛，被誉为「机器人界的 Transformers」。',
    url: 'https://huggingface.co',
    source: 'Hugging Face',
    source_type: '开源项目',
    category: 'tool',
    tags: ['Hugging Face', '机器人', '开源'],
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    likes: 278,
    views: 13500,
    comments: 45,
    engagement: 323,
  },
]
